model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128


data_params:
  data_path: "/data0/canbin/dataset"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.000025
  manual_seed: 1265

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  
gpu_params:
  accelerator: 'gpu'
  devices: [3]

test_run_config:
  limit_train_batches: 0.1
  limit_val_batches: 1