model_params:
  name: 'VQVAE'
  in_channels: 3
  embedding_dim: 64
  num_embeddings: 512
  img_size: 64
  beta: 0.25
  dataset_var: 1
  residual_hidden_channels: 32
  epsilon: 0.00001
  use_ema: True
  decay: 0.99

data_params:
  data_path: "/data0/canbin/dataset"
  train_batch_size: 32
  val_batch_size:  32
  patch_size: 32
  num_workers: 4


exp_params:
  LR: 0.0003
  weight_decay: 0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

logging_params:
  save_dir: "logs/"
  name: "VQVAE"

gpu_params:
  accelerator: 'gpu'
  devices: [2, 3]

test_run_config:
  limit_train_batches: 0.1
  limit_val_batches: 1
